### ISSUE TITLE
getTerminalAttributes error when using getContents

### ISSUE THREAD

**Issue by wcaleb** [jtdaugherty/vty-ui#65] opened 2015-03-10 13:00 UTC
Below is a minimal `List` widget program mainly copied from one of the demos. It works fine when run like this:

```haskell
main :: IO ()
main = do 

   let testLines = ["Line 1", "Line 2", "Line 3"]

   lst <- newList 1
   setSelectedUnfocusedAttr lst $ Just (fgColor brightGreen)
   listMsg <- plainText T.empty
   selector <- vLimit 40 lst

   lst `onSelectionChange` \ev ->
      case ev of
        SelectionOn _ k _ -> setText listMsg $ T.pack $ "You selected: " ++ k
        SelectionOff -> return ()

   lst `onItemActivated` \(ActivateItemEvent _ s _) ->
      setText listMsg $ T.pack $ "You activated: " ++ s

   mainBox <- vBox selector listMsg

   fgr <- newFocusGroup
   fgr `onKeyPressed` \_ k _ -> do
         case k of
           KEsc -> exitSuccess
           _ -> return False

   addToFocusGroup fgr lst

   ui <- centered =<< hLimit 70 mainBox

   forM_ testLines $ \s ->
      (addToList lst s =<< (plainText $ T.pack s))


   c <- newCollection
   _ <- addToCollection c ui fgr

   runUi c defaultContext 
 ````

But the program breaks if I try to `getContents` from STDIN and load those contents into the list. For example, like this:

`````
   contents <- getContents
   let testLines = lines contents
`````

When I do that I seem to get this error:

`````
getTerminalAttributes: invalid argument (Bad file descriptor)
`````

I'm fairly new to Haskell so it's probable that I'm misunderstanding something basic about I/O here. Do you have any pointers? Or is this an issue/limitation of `vty-ui`?

**Comment by wcaleb** [comment] 2015-03-10 16:00
As an added note, binding `getLine` or a file handle to contents works fine, so the problem seems to be specifically with STDIN.

**Comment by jtdaugherty** [comment] 2015-03-10 16:51
Very interesting! I don't have any insights off the top of my head, but I will look into it.

**Comment by wcaleb** [comment] 2015-03-10 17:11
I found [this very old bug ticket](http://trac.haskell.org/haskeline/ticket/31) that seemed relevant, but I don't know if it will be helpful.

**Comment by jtdaugherty** [comment] 2015-03-11 04:40
Can you run this with `strace` to capture the system call that generates the error?  It should shed some more light on what is going on.

With that said, using this approach in production, as it were, might prove to be problematic even if it doesn't cause this behavior.  To know whether data piped to this program would be destined for such a `getContents` call or instead be destined for processing in keyboard event handlers would be hard to puzzle out - you'd probably have to read a fixed number of bytes from `stdin` before starting the `vty-ui` event loop.  This is all to say that the meaning of "pipe data to a `vty-ui` program" might not be clear in general if you're doing some reads before event loop starts.

**Comment by wcaleb** [comment] 2015-03-11 14:42
I'm on a Mac, but I can run `dtruss`. The last system call produced is:

```
ioctl(0x3, 0x80086804, 0x7FFF65CE8568)		 = 0 0
```

Thanks for the tip about the code, too. I guess a better approach would be to write STDIN to a tmpfile and then load the file's contents into the List widget?

**Comment by wcaleb** [comment] 2015-03-11 15:08
Actually it looks like I can't even write STDIN contents to a tempfile without getting the same error.

**Comment by jtdaugherty** [comment] 2015-03-11 16:47
`dtruss` didn't decode the `ioctl` request for us, but on Linux `strace` reports that this is probably a `TCGETS` request, i.e., `tcgetattr`. I don't know exactly why it's failing, but I can reproduce this problem with
```
main :: IO ()
main = do
    v <- getContents
    let ls = lines v
    print ls
    getTerminalAttributes (Fd 0)
    return ()
```
and there are many, many Google results suggesting that doing this with `stdin` is not advisable.  My theory at this point is that perhaps reading from `stdin` changes it so that it's no longer a synonym for the controlling terminal, which causes `ioctl` calls on it to fail (since the particular `ioctl` being requested expects a terminal).

So, yeah, it sounds like the "fix" for this problem is to read from a file, not `stdin`.

**Comment by jtdaugherty** [comment] 2015-12-26 21:42
FYI, since this package has been deprecated in favor of brick (http://hackage.haskell.org/package/brick) I'm closing open vty-ui tickets since I'd prefer to redirect users to that new (and better) library instead of spending energy on vty-ui.  (If someone wants to take up the mantle and fix them, we can just re-open the issues.)

**Closed by jtdaugherty** 2015-12-26 21:42 UTC
